language: node_js

env:
  NODE_ENV=development
  TESTING_ENV=true

node_js:
  - "6"

before_install:
  - sudo add-apt-repository ppa:rethinkdb/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install rethinkdb -y

services:
  - redis-server

before_script
  - rethinkdb --daemon
  - npm install -g mocha
  - npm install -g gulp

script:
  - node server.js
  - npm run nyc
