language: node_js

env:
  NODE_ENV=development TESTING_ENV=true

node_js:
  - "6"

before_install:
  - source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
  - wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - sudo apt-get update -y
  - sudo apt-get install rethinkdb -y

services:
  - redis-server

before_script:
  - rethinkdb --daemon
  - npm install -g mocha
  - npm install -g gulp

script:
  - node server.js
  - npm run nyc
