language: node_js

env:
  NODE_ENV=development
  TESTING_ENV=true

node_js:
  - "6"

before_install:
  - sudo add-apt-repository ppa:rethinkdb/ppa && sudo apt-get update && sudo apt-get install rethinkdb

services:
  - redis-server
  - mysql

before_script:
  - npm install -g mocha
  - npm install -g gulp

script:
  - node server.js
  - npm run nyc
